apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5ekNDQWJPZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EZ3hNekU0TXpRMU0xb1hEVE13TURneE1URTRNemsxTTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHArClJGbThyd0Y1d2ZYWUFUMWcrd3J4UkZGSFE4T21aN29XZDVzMGZrRTlveEpxUENsc3dZYVpKVHNoajNzNHh3WUQKc2s0ZnRtRGdmTUdoQ05KcVBnVGMxZmNKZ0JhTGx2cjdRenB4NFo0cHFlM2g5MnJXMURCTkxIdTE4ZTRWNXFwWQpaUzB4T29TYm03WFluVWhrb1dRWlhmZzViUnhGVTZYRUc3c2ZCblM1STFOTEJzWkF6L1pRNjZBWnZwdUxZRG95CjZqSkZmOU1TRy96cUh4UHVtRzBrRXBoWmNBT0dlUDJxclRuQ1Qwc0NvK0doZVBUdEI2anNCcGZOdGpGMnJPZWMKVmI3STlGWnRDQnRKeWQvdkU2WDd6QzZOdGczenAvVnM2ZTVsclY3QjZ5Qy9JanJsRkd2MFdET1R2S3p2YkJsdApZaSt1elptTkE3dGpVbDl6dkljQ0F3RUFBYU1tTUNRd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSCtGWm1UaXdhRTZkOEFPRVVsNE4ydjAKS3h2OXNXNjVlNyt1UkFwWkMrMlBra1dRczZ5WHlqaWpUTDZjWk9FTkpKdmQwLzlmNEJwREkwczJxWVFQUVhzcApKMVFKemxpSUgyOEpvUmdiVWtiejBvcU0yQS95aUJTcjExU2xsTjU1bysvNStTbzhSdTN1YzlWcVluR2NpV0JJClQ0RkgrNXJLSlU2OUNSNHR1WXU4UEFQdDlDS0s5SzhPYU5LbHZKSHBnVldEeU9XR0VuMnFLSng2UDBQYjZNWDMKN05iSklaRUpRb2RPd1h4OUdTS25Fak9Uc3VLbm9HTSs0WjFyYmNuTkRBbWErZmtkbjNId0JIQ3M2b2IzY1AzeQplUVNGa0hjK1RGN01LaFNjSXdEL3IxTjVPUDFubWFnU0dyZDdQOWtTYjFTb3ZMMXVIb3d4WDNuM3YybXN6YW89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://o9gl2g2m3wnhc4wnidevrwkdjmrh-k8s-1367050115.us-east-2.elb.amazonaws.com:443
  name: awscluster
contexts:
- context:
    cluster: awscluster
    namespace: robot
    user: awscluster
  name: awscluster
current-context: awscluster
kind: Config
preferences: {}
users:
- name: awscluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - cluster
      - generate-token-v2
      command: tmc
      env:
      - name: CLUSTER_UID
        value: c:01EFMHRX2DRNHB47TMH34XXE8C
      - name: CLUSTER_RID
        value: rid:c:e656072b-e8a6-49ca-84bb-8ecbc55b1301:global:awscluster
